services:
  app:
    build: .
    container_name: thoth-backend
    entrypoint: .docker/entrypoint.sh
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/home/node/app
    env_file:
      - .env

