services:
  app:
    build: .
    container_name: thoth-backend
    entrypoint: .docker/entrypoint.sh
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/home/node/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.18
    container_name: thoth-db
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env

  storage:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    command: server /thoth-storage --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-storage:/thoth-storage

volumes:
  pg-data:
    external: true
  minio-storage:
    external: true
