version: '3'

services:
  app:
    build: .
    container_name: thoth-backend
    entrypoint: .docker/entrypoint.sh
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/home/node/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.2-alpine3.18
    container_name: thoth-db
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg-data:
    external: true
