name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: Deployment
    steps:
      - uses: actions/checkout@v4
      - name: Use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Rebuild bcrypt
        run: npm rebuild bcrypt --from-source
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: ${{ secrets.SSH_ARGS }}
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: '/dist/, /node_modules/'
          SCRIPT_AFTER: |
            touch ${{ secrets.REMOTE_TARGET }}/.env
            echo NODE_ENV=${{ vars.NODE_ENV }} > ${{ secrets.REMOTE_TARGET }}/.env
            echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DEFAULT_ADMIN_USER=${{ secrets.DEFAULT_ADMIN_USER }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo MINIO_ENDPOINT_URL=${{ secrets.MINIO_ENDPOINT_URL }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo MINIO_BUCKET_NAME=${{ secrets.MINIO_BUCKET_NAME }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo MINIO_SIGNED_EXPIRES_IN=${{ secrets.MINIO_SIGNED_EXPIRES_IN }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo ORACLE_HOST=${{ secrets.ORACLE_HOST }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo ORACLE_PORT=${{ secrets.ORACLE_PORT }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo ORACLE_DATABASE=${{ secrets.ORACLE_DATABASE }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo ORACLE_USER=${{ secrets.ORACLE_USER }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo ORACLE_PASSWORD=${{ secrets.ORACLE_PASSWORD }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo ORACLE_WALLET_PASSWORD=${{ secrets.ORACLE_WALLET_PASSWORD }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo ORACLE_CONNECT_STRING=${{ secrets.ORACLE_CONNECT_STRING }} >> ${{ secrets.REMOTE_TARGET }}/.env
          SCRIPT_AFTER_REQUIRED: true
