name: Deploy

on:
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    environment: Deployment
    steps:
      - uses: actions/checkout@v4
      - name: Use Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install npm dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Rebuild bcrypt
        run: npm rebuild bcrypt --from-source
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: ${{ secrets.SSH_ARGS }}
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: '/dist/, /node_modules/'
          SCRIPT_AFTER: |
            touch ${{ secrets.REMOTE_TARGET }}/.env
            echo NODE_ENV=${{ vars.NODE_ENV }} > ${{ secrets.REMOTE_TARGET }}/.env
            echo SENTRY_DSN=${{ secrets.SENTRY_DSN }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DEFAULT_ADMIN_USER=${{ secrets.DEFAULT_ADMIN_USER }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo STORAGE_ENDPOINT_URL=${{ secrets.STORAGE_ENDPOINT_URL }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo STORAGE_ACCESS_KEY=${{ secrets.STORAGE_ACCESS_KEY }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo STORAGE_SECRET_KEY=${{ secrets.STORAGE_SECRET_KEY }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo STORAGE_BUCKET_NAME=${{ secrets.STORAGE_BUCKET_NAME }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo STORAGE_SIGNED_EXPIRES_IN=${{ secrets.STORAGE_SIGNED_EXPIRES_IN }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DB_HOST=${{ secrets.DB_HOST }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DB_PORT=${{ secrets.DB_PORT }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DB_NAME=${{ secrets.DB_NAME }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DB_USER=${{ secrets.DB_USER }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DB_WALLET_PASSWORD=${{ secrets.DB_WALLET_PASSWORD }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DB_WALLET_PATH=${{ secrets.DB_WALLET_PATH }} >> ${{ secrets.REMOTE_TARGET }}/.env
            echo DB_CONNECT_STRING=${{ secrets.DB_CONNECT_STRING }} >> ${{ secrets.REMOTE_TARGET }}/.env
          SCRIPT_AFTER_REQUIRED: true
